# Gemfile
source "https://rubygems.org"

# Utilise GitHub Pages pour Jekyll et ses dépendances
gem "github-pages", "~> 232", group: :jekyll_plugins

# Plugins utilisés dans ta configuration
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "just-the-docs"
end

# Dépendances pour Windows (si tu développes localement sous Windows)
platforms :mingw, :x64_mingw, :mswin do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
  gem "wdm", "~> 0.1.1"
end

# Lock http_parser.rb gem to v0.6.x sur JRuby
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]
gem "webrick", "~> 1.8"
